# Generated by Django 3.2.9 on 2021-11-09 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='imprenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imprenta', verbose_name='editorial'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='sinopsis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
