# Generated by Django 3.2.9 on 2021-11-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_libro_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_per', models.ImageField(upload_to='', verbose_name='Imgen ID')),
                ('edad', models.IntegerField(max_length=3)),
            ],
        ),
    ]
